### ISSUE TITLE
[Bug] Upgraded to majestic 1.4.0, errors with no message in terminal.

### ISSUE THREAD

**Issue by M4cs** [Raathigesh/majestic#123] opened 2019-04-15 15:27 UTC
Bug 🐛 

- Version of Majestic: 1.4.0
- Version of Jest: 20.0.3
- Version of Node: 8.15.1
- Operating System: macOS 10.14

Updated from 1.3.0 to 1.4.0 with `yarn upgrade majestic@1.4.0 --dev` and it won't load in my browser anymore. Says to check terminal but there is no log or error in the terminal and the server keeps running.

**Comment by M4cs** [comment] 2019-04-15 15:29
Can confirm it's the 1.4.0 update.

Ran `yarn upgrade majestic@1.3.0 --dev` to downgrade and it's working now.

**Comment by huyhqit** [comment] 2019-04-15 18:12
Hi, @M4cs I downgraded to `majestic@1.3.0` but terminal did not notify error

- Version of Majestic: 1.3.0
- Version of Jest: 24.5.0
- Version of Node: 10.15.2
- Operating System: Window 10

**Comment by Raathigesh** [comment] 2019-04-16 00:01
Can you see anything in the browser console?

**Comment by huyhqit** [comment] 2019-04-16 00:28
No, my browser was notify “oops, some thing went wrong. Check the terminal for exact errer mesange!”

**Comment by huyhqit** [comment] 2019-04-16 08:10
oh, my browser console https://ibb.co/7NhPXZN

**Comment by Raathigesh** [comment] 2019-04-16 09:34
@huyhqit Unfortunately I was able to reproduce it. Would you be able to help me find the issue? A sample repo where this is reproducible would be helpful.

**Comment by krazylegz** [comment] 2019-04-16 12:28
I'm able to reproduce this without any changes to https://github.com/GabrieleRomeo/ES6-Professional-starter-kit . I can do:
`git clone https://github.com/GabrieleRomeo/ES6-Professional-starter-kit.git ; cd ES6-Professional-starter-kit ; yarn ; npx majestic`
to replicate the issue. My console has:
```
TypeError: Cannot read property 'projectRoot' of undefined
    at Yl (ui.bundle.js:21)
    at Jo (ui.bundle.js:42)
    at Li (ui.bundle.js:42)
    at Ha (ui.bundle.js:42)
    at Ka (ui.bundle.js:42)
    at Pl (ui.bundle.js:42)
    at Tl (ui.bundle.js:42)
    at xl (ui.bundle.js:42)
    at ui.bundle.js:42
da @ ui.bundle.js:42
```

**Comment by M4cs** [comment] 2019-04-16 13:44
Same errors as above for me.

**Comment by robotanz** [comment] 2019-04-16 14:12
Same issue for me...

**Comment by Raathigesh** [comment] 2019-04-16 21:47
Thanks, @krazylegz for the repository. I can reproduce the issue. Will get a fix in soon.

**Comment by Raathigesh** [comment] 2019-04-17 10:00
Fixed and released in https://github.com/Raathigesh/majestic/releases/tag/v1.4.1.

Please do test it and reopen if the issue is still there.

**Closed by Raathigesh** 2019-04-17 10:00 UTC

**Comment by M4cs** [comment] 2019-04-17 10:37
Will test today at work. Thanks for the fast fixes!

**Comment by krazylegz** [comment] 2019-04-17 12:19
Working for me now, thank you so much!

**Comment by ziofat** [comment] 2020-05-18 12:28
I have this issue with 1.7.0. @Raathigesh

**Comment by inlightmedia** [comment] 2021-06-16 21:25
I'm seeing this with 1.8.0

**Comment by imkarmadev** [comment] 2021-11-29 13:31
same in 1.8.1
