### ISSUE TITLE
[Question] What do purple colored icons mean?

### ISSUE THREAD

**Issue by nshaikhinurov** [Raathigesh/majestic#85] opened 2019-03-28 18:06 UTC
Couldn't figure out what does the purple color of describe blocks (box) and test (lightning) icons mean. I suppose purple is for tests that have not completed yet. 

Also looks like there is a bug/unsupported behaviour. I'm using decorators with Babel and reflect-metadata. Majestick couldn't manage to render correct filename and shows 12 passing tests on header and irreevant body with results from another test file as seen on screenshot below.

Attaching screenshot:
![image](https://user-images.githubusercontent.com/4477911/55181241-1d0b9080-51ad-11e9-9cd3-2e86b6fefa78.png)

**Comment by M4cs** [comment] 2019-03-28 18:20
I believe it means the successful results have been viewed by you and it is just confirming that they are still passing and the same test names.

**Comment by Raathigesh** [comment] 2019-03-29 08:11
Purple means the default state, which is Majestic couldn't find a result to that test. This looks like a bug. Decorators or babel or reflect-metadata shouldn't affect how majestic shows the results since we didn't do anything in particular than just invoke jest.

It would greatly help if you could put together a small repo where this issue is reproducible.

**Comment by Raathigesh** [comment] 2019-04-02 10:38
Closing this for now. Feel free to reopen with an example repo.

**Closed by Raathigesh** 2019-04-02 10:38 UTC
Labels: ❔ Question
