### ISSUE TITLE
No test tree

### ISSUE THREAD

**Issue by JohnathonLamOF** [Raathigesh/majestic#46] opened 2018-02-14 00:03 UTC
## Is this a bug report or a feature request?

Please specify whether this is a feature request 🎁 or a bug 🐛.

## Version Info

- Version of Majestic: 0.2.0
- Version of Jest: "jest": "^22.2.2"
- Version of Node: 8.9.4
- Operating System: Windows 10

## Reproduction Repo

Here is my jest configuration `"jest": {
        "verbose": true,
        "collectCoverage": true,
        "coverageReporters": ["html"]
    }`

My jest config is really minimal, so my tests are able to run, however I get nothing in the sidebar for all my tests, and when I click show failures nothing happens.  My tests are in a directory formatted like this __tests__/{components}/{componentname}.tests.js.

**Comment by brunocroh** [comment] 2018-02-22 14:29
same issue here

Version of Majestic: 0.2.0
Version of Jest: "jest": "^22.1.3"
Version of Node: 8.9.3
Operating System: Windows 10

**Comment by Raathigesh** [comment] 2018-03-26 09:45
Opps! I can reproduce the issue. Will have a look!

**Comment by Raathigesh** [comment] 2018-06-13 00:18
Hey Guys,

Sorry, I did not investigate this issue further on the current version because been working on a majestic rewrite. It will be distributed as an npm module.

If you like to help test the early build of the new majestic, please follow the steps.

- Install majestic globally with `yarn global add majestic@alpha` or `npm install majestic@alpha -g`
- Go to a directory with Jest configured and run majestic in your terminal
- You should see the UI in your default browser

I would appreciate any kind of feedback on this. Please let me know if you run into any issues.

**Comment by Raathigesh** [comment] 2018-09-05 10:26
Hey @cipriancaba, would you please be able to let me know where you have the jest config? if you could create a repo where the issue is reproducible, that would be super helpful 👍

**Comment by cipriancaba** [comment] 2018-09-05 10:27
It’s just a simple create-react-app

**Comment by cipriancaba** [comment] 2018-09-05 10:28
Also, the left bar appears for a fraction second and then disappears
immediately.. will try to provide the repo, thank you

**Comment by Raathigesh** [comment] 2018-09-05 10:36
@cipriancaba if it's create-react-app, then no need of a repo. I can take a look at it. You can press Ctrl +B or Cmd +B to bring the sidebar back. This should be documented and I'm working on finishing the website and docs.

**Comment by cipriancaba** [comment] 2018-09-05 16:30
@Raathigesh Cmd+B did the trick.. I think there might be a need for UI element to trigger the tree.. Also if the tree is not present and you run the tests, the screen stays empty, which maybe is a bit counter-intuitive.. Other than that, great work 👍

**Comment by Raathigesh** [comment] 2018-09-06 22:56
This is fixed in v1.1.0. Feel free to open issues if you feel like there are potential improvements or features that would make a difference to your testing workflow 👍 Closing this for now.

**Closed by Raathigesh** 2018-09-06 22:56 UTC
