### ISSUE TITLE
onClick Watch, see in terminal TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by micahstubbs** [Raathigesh/majestic#113] opened 2019-04-04 22:34 UTC
onClick Watch, I see in terminal `TypeError: Cannot read property 'length' of undefined`

## Is this a bug report or a feature request?
bug report 

## Version Info

- Version of Majestic: `v1.2.23`
- Version of Jest:  `23.6.0`
- Version of Node: `v8.11.3`
- Operating System: `macOs 10.14.4`

## Reproduction Repo

repro repo coming soon 🤞 

```bash
$ npx majestic
npx: installed 29 in 1.974s
⚡  Majestic v1.2.23 is running at http://localhost:4000
/Users/m/.npm/_npx/23768/lib/node_modules/majestic/dist/server/index.js:33749
    this.length = input.length;
                        ^

TypeError: Cannot read property 'length' of undefined
    at State.init (/Users/m/.npm/_npx/23768/lib/node_modules/majestic/dist/server/index.js:33749:25)
    at new Tokenizer (/Users/m/.npm/_npx/23768/lib/node_modules/majestic/dist/server/index.js:33806:16)
    at new UtilParser (/Users/m/.npm/_npx/23768/lib/node_modules/majestic/dist/server/index.js:34913:1)
    at new NodeUtils (/Users/m/.npm/_npx/23768/lib/node_modules/majestic/dist/server/index.js:35048:1)
    at new LValParser (/Users/m/.npm/_npx/23768/lib/node_modules/majestic/dist/server/index.js:35086:1)
    at new ExpressionParser (/Users/m/.npm/_npx/23768/lib/node_modules/majestic/dist/server/index.js:35410:1)
    at new StatementParser (/Users/m/.npm/_npx/23768/lib/node_modules/majestic/dist/server/index.js:37022:1)
    at new Parser (/Users/m/.npm/_npx/23768/lib/node_modules/majestic/dist/server/index.js:38494:5)
    at new <anonymous> (/Users/m/.npm/_npx/23768/lib/node_modules/majestic/dist/server/index.js:33023:26)
    at new <anonymous> (/Users/m/.npm/_npx/23768/lib/node_modules/majestic/dist/server/index.js:30585:5)
```

**Comment by Raathigesh** [comment] 2019-04-04 22:40
Unfortunately, this error alone doesn't explain much. Would you be able to reproduce this in a minimal example, please?

**Comment by ziofat** [comment] 2019-04-09 02:53
I got this error too. The different is I did not click on watch.
The error occur occasionally.

Happend in v1.2.23 and v1.3.

![image](https://user-images.githubusercontent.com/8521174/55769995-497cb200-5ab5-11e9-94f0-a4661f5addc7.png)

**Comment by Raathigesh** [comment] 2019-04-09 03:53
@ziofat Does the error breaks majestic and makes in not usable?

**Comment by ziofat** [comment] 2019-04-09 03:57
@Raathigesh Yes it does. The process exited with non-zero code and the buttons in web UI did not respond to any clicks.

**Comment by Raathigesh** [comment] 2019-04-09 04:11
It looks like the babel parser is failing to parse. Will take a look.

**Comment by Raathigesh** [comment] 2019-04-15 11:41
When there are syntax errors, we handle it better in version [1.4](https://github.com/Raathigesh/majestic/releases/tag/v1.4.0).

I'm closing it for the time being but feel free to reopen it the issue is not resolved.

**Closed by Raathigesh** 2019-04-15 11:41 UTC
Labels: 🐞 Bug
